name: fold_comic_viewer
description: A Galaxy Fold optimized comic & manga viewer with dual-page and margin crop features.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  archive: ^3.6.1
  shared_preferences: ^2.3.2
  file_picker: ^8.1.7
  permission_handler: ^11.3.1
  path_provider: ^2.1.4
  path: ^1.9.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
